version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  spring-boot-app:
#    image: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8181:8181"
    environment:
      MYSQL_HOST: mysql

